# Generated by Django 4.2.1 on 2023-06-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiobook',
            name='file_link',
        ),
        migrations.RemoveField(
            model_name='audiobook',
            name='file_size',
        ),
        migrations.AddField(
            model_name='audiobook',
            name='audio_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kitob audio linki'),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='audio_size',
            field=models.CharField(default=1, max_length=255, verbose_name='Audio hajmi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filebook',
            name='file_size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fayl hajmi'),
        ),
    ]
