# Generated by Django 4.2.1 on 2023-06-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0004_alter_filebook_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filebook',
            name='type',
            field=models.CharField(max_length=80, verbose_name='Kitob formati'),
        ),
    ]
