# Generated by Django 4.2.1 on 2023-06-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0006_audiobook_slug_filebook_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filebook',
            name='description',
            field=models.TextField(verbose_name='Kitob nomii'),
        ),
    ]
