# Generated by Django 4.0 on 2023-07-14 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0008_alter_audiobook_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiobook',
            name='category',
        ),
        migrations.RemoveField(
            model_name='audiobook',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='audiobook',
            name='type',
        ),
        migrations.RemoveField(
            model_name='filebook',
            name='category',
        ),
        migrations.RemoveField(
            model_name='filebook',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='filebook',
            name='type',
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_book', to='book_api.author'),
        ),
        migrations.AlterField(
            model_name='filebook',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_book', to='book_api.author'),
        ),
    ]
