# Generated by Django 4.0 on 2023-07-20 12:28

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0011_alter_filebook_description_tsvector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filebook',
            name='description_tsvector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
