# Generated by Django 4.0 on 2023-07-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0012_alter_filebook_description_tsvector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filebook',
            name='description_tsvector',
        ),
    ]
